services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=demobase
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_USER=user
    ports:
      - 3308:3306
