name: Gradle Package

on:
    push:
        branches:
            - main
jobs:
    build-deploy:
        name: Build and Deploy
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: "21"
                  distribution: "temurin"

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

            - name: Build with Gradle Wrapper
              working-directory: backend
              run: |
                  chmod +x gradlew
                  ./gradlew build

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKER_ACCESS }}

            - name: Build and push the Docker image
              uses: docker/build-push-action@v6
              with:
                  context: .
                  file: Dockerfile
                  push: true
                  platforms: linux/amd64
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/spring-app-demo:latest

    deploy-backend:
        name: Deploy Backend
        runs-on: self-hosted
        needs: [build-deploy]
        steps:
            - name: create deployment folder
              run: ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} "mkdir -p ~/spring-app-demo/backend"

            - name: copy backend files
              run: scp docker-compose.yml ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }}:~/spring-app-demo/backend/docker-compose.yml

            - name: deploy
              run: |
                  ssh ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }}
                  cd ~/spring-app-demo/backend
                  docker-compose -f docker-compose.yml pull -q
                  docker-compose -f docker-compose.yml up -q
